### PR TITLE
Main codebase have some files

### PR DESCRIPTION
**Pull request by tadaspetra**

### CODE REVIEW

**Review by rodriguezmatirp — APPROVED** [review]

**Comment by Orion-33** [comment]
What was the issue with the convene app....it looked fire.........

**Comment by tadaspetra** [comment]
I had it set up in a separate repo, and then took it private because I was working with a lot of secret keys and stuff and I was too lazy to set it up properly. But now I definitely regret doing that. Planning to reopen source it but have to go through and set up all the secrets properly

**Comment by Orion-33** [comment]
OK.....that sounds great. So if you need any help I can help ......your app
inspired me because I wish we had one with those exact features.....so I
tried to make one but am running into various errors....hope maybe you
could help me out...if you have time....

Looking to hear from you soon.

Regards Laban Orina

**Comment by tadaspetra** [comment]
in a separate repo now

**Pull request closed without merging**
